### ISSUE TITLE
Multiple PHPUNIT plugin definitions ignored

### ISSUE THREAD

**Issue by benr77** [Block8/PHPCI#1013]
Hi,

I have a lot of functional tests in my project. Memory usage of PHPUnit is quite high - well over 1GB.

What I have done is split my tests in to test suites - this way I can break down the tests in to smaller groups, and this brings the memory consumption down for each group as PHPUnit starts all over again when you move on to the next test suite. This all works fine from the command line.

However, in my phpci.yml I have then defined the phpunit plugin 3 times, once for each test suite as follows:

```
test:
  php_unit:
    config:
      - "app/phpunit.xml"
    args: "--testsuite Group1"
  php_unit:
    config:
      - "app/phpunit.xml"
    args: "--testsuite Group2"
  php_unit:
    config:
      - "app/phpunit.xml"
    args: "--testsuite Group3"
```

The idea of course is that phpci can then just run the three tests suites one after another.

The problem is that only the first call is run and only tests from the test suite Group1 are executed.

Can it be configured to run multiple phpunit plugin definitions?

Thanks
