### ISSUE TITLE
PHP Copy/Paste detector - allow errors option?

### ISSUE THREAD

**Issue by wheelsandcogs** [Block8/PHPCI#1043]
Is there a way to include the output from the phpcpd plugin but not have it fail the build, like you can with phpci? The wiki has no "allowed_errors" option: https://github.com/Block8/PHPCI/wiki/PHP-Copy-Paste-Detector-Plugin

I have tried:

```
php_cpd:
        standard: "PSR2"
        allowed_warnings: -1
        allowed_errors: -1
```

but my build still fails.
