### ISSUE TITLE
Which enviroment

### ISSUE THREAD

**Issue by sobi3ch** [Block8/PHPCI#1045]
Sorry if this is wrong place to ask questions but I couldn't find anything better. 

How can I distinguish current environment (dev, stage, production)? I have my config file `phpci.yml` in the root of my project (as wiki told me). I know I can create in PHPCI UI different projects for different branches like dev/stage/prod, but then all this branches have in root dir same `phpci.yml` config file. I hope this make sense.

**Comment by dancryer** [comment]
There's no way to do this currently. In v1.7 (the next release), you'll be able to add stages that are specific to certain branches, like so:

```yml
# Test config for all branches
test:
    php_unit:
        allow_failures: 10

# Test config for release branch
branch-release:
    run-option: 'replace'
    test:
        php_unit:
            allow_failures: 0
```
