### ISSUE TITLE
Issue running PHPUnit

### ISSUE THREAD

**Issue by phillydogg28** [Block8/PHPCI#1050]
I am having an issues getting our project to test properly. The first issue I had was related to the path, but I was able to fix with `chdir` in our bootstrap file. Now the only output I see is:
```
Cloning into '/var/www/phpci/PHPCI/build/46'...
Working copy created: /
RUNNING PLUGIN: php_unit
PLUGIN: FAILED
BUILD FAILED
Removing Build.
```
I originally had PHPCI pulling the code from Github, but pulled a local copy manually to test against. With the local copy I was able to run `php vendor/phpunit/phpunit/phpunit -c ~/code/REPONAME/httpdocs/tests/phpunit.xml --tap` from `/var/www/phpci` and see the output. My `phpci.yml` file is:
```
build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
test:
    php_unit:
        directory: "httpdocs/tests"
        args: "--bootstrap 'httpdocs/tests/bootstrap/bootstrap_phpunit.php' --configuration 'httpdocs/tests/phpunit.xml'"
```
