### ISSUE TITLE
TAP parser says Invalid TAP string on codeception

### ISSUE THREAD

**Issue by mikk150** [Block8/PHPCI#1052]
I tried to build basic Yii2 application (https://github.com/yiisoft/yii2-app-basic)  
```
TAP version 13 
ok 1 - tests\codeception\unit\models\ContactFormTest::testContact 
ok 2 - tests\codeception\unit\models\LoginFormTest::testLoginNoUser 
ok 3 - tests\codeception\unit\models\LoginFormTest::testLoginWrongPassword 
ok 4 - tests\codeception\unit\models\LoginFormTest::testLoginCorrect 
1..4 
ok 5 - ensure that about works (AboutCept) 
ok 6 - ensure that contact works (ContactCept) 
ok 7 - ensure that home page works (HomeCept) 
ok 8 - ensure that login works (LoginCept) 
1..8 
ok 9 - ensure that about works (AboutCept) 
ok 10 - ensure that contact works (ContactCept) 
ok 11 - ensure that home page works (HomeCept) 
ok 12 - ensure that login works (LoginCept) 
1..12  
{"buildID":"9"} []

[2015-08-31 12:02:17] DaemoniseCommand.ERROR: Exception: Invalid TAP string, number of tests does not match specified test count. {"exception":"[object] (Exception(code: 0): Invalid TAP string, number of tests does not match specified test count. at /var/www/phpci/PHPCI/Plugin/Util/TapParser.php:76)","buildID":"9"} []
```

```yaml
build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
    ignore:
        - "vendor"
        - "tests"

setup:
    composer:
        action: "install"
    shell:
        - "cd %BUILD_PATH%/tests && codecept build"
        - "cd %BUILD_PATH%/web && php -S localhost:8080 >/dev/null 2>&1 & echo $! > %BUILD_PATH%/server.pid"

test:
    codeception:
        config: "tests/"
        log_path: "tests/codeception/_output"
    php_mess_detector:
        allow_failures: true
    php_code_sniffer:
        standard: "PSR2"
    php_cpd:
        allow_failures: true

complete:
    shell: 
        - "kill `cat %BUILD_PATH%/server.pid`"
```
