### ISSUE TITLE
Exception: Could not process PHPMD report XML

### ISSUE THREAD

**Issue by mstaack** [Block8/PHPCI#1056]
```
        AUSGEFÜHRTES PLUGIN: php_mess_detector
        PHP Catchable fatal error:  Argument 1 passed to
        PDepend\Source\Parser\UnexpectedTokenException::__construct() must be an instance of
        PDepend\Source\Tokenizer\Token, integer given, called in
        /var/www/phpci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHP
        arser.php on line 5494 and defined in /var/www/phpci/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Parser/UnexpectedTokenException.php on line 61


        Exception: Could not process PHPMD report XML.
        PLUGIN: FEHLGECHLAGEN
        ```

phpci.yml
```
    php_mess_detector:
        path: "protected"
        rules:
          - "cleancode"
          - "controversial"
          - "codesize"
          - "design"
          - "naming"
          - "unusedcode"
        allow_failures: true
        zero_config: true
```
php-sources @  'protected' folder in doc root

any idea whats wrong?
