### ISSUE TITLE
Commit Notifications From Forks?

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#1088]
@jimmycleuren For some reason I am getting emails from your PHPCI fork. It appears it is sending emails out when it shouldn't be, as I am getting notifications from your branch. I am guessing you are running it through PHPCI to check? Do you have it configured so send emails out to each committer?

**Comment by tvbeek** [comment]
That is because of the failure part in .phpci.yml and you are member of php-ci@googlegroups.com

```
failure:
  email:
    committer: true
    cc: ["php-ci@googlegroups.com"]
```
