### ISSUE TITLE
Slack notifications always failed

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#1090]
Hi

I'm using the `Slack Notifier` plugin and every time a build runs and completes, no matter what status, the message in my Slack channel is always:

`Status: Failed`

Does anyone know why this is?

**Comment by mikebronner** [comment]
Are you using the laster updates to `master` from yesterday?

**Comment by REBELinBLUE** [comment]
Hmm, very odd.

Definitely working for me today

!(mine)[https://s3.amazonaws.com/f.cl.ly/items/1f1h0o0y0s091d0p1T26/Image%202015-10-14%20at%205.26.47%20p.m..png]

**Comment by mikebronner** [comment]
Confirmed working here as well:
![screen shot 2015-10-14 at 09 49 24](https://cloud.githubusercontent.com/assets/1791050/10491001/f5781584-7258-11e5-9f96-924c9dca0b19.png)

**Comment by craigwillis85** [comment]
I did a git pull of master earlier today.

This has never returned a `success` message ever since I've used it, which has been about 2 months.

**Comment by mikebronner** [comment]
Paste you slack plugin config portion of phpci.yml here. It should look something like:

```yml
complete:
  slack_notify:
    webhook_url: "https://hooks.slack.com/services/<web-hook-id-here>"
    room: "#<channel-name-here>"
```
