### ISSUE TITLE
PHPLint Task

### ISSUE THREAD

**Issue by tobiastom** [Block8/PHPCI#111]
Not sure if it would duplicate existing functionality, but having a lint task that will simply check the syntax of files might be nice:

```
lint:
    directories:
        directoryA:
            - .php
            - .html
        directoryB:
            - *
    files:
        - lala.php
        - foo.html
```

The task would search inside directories for files ending with the given extensions. Each file would then be executed with `php -l <file>`.

I'm not happy with the structure of the definition, but like this it covers most features I would expect.
