### ISSUE TITLE
Implement Webhooks

### ISSUE THREAD

**Issue by meadsteve** [Block8/PHPCI#113]
From a discussion in #67 it seems sensible to implement webhooks. 

I imagine these being available in all plugins and configurable to run pre and post execution so the yml file would have something like:

``` yml
php_unit:
        config:
            - "PHPUnit-all.xml"
            - "PHPUnit-ubuntu-fix.xml"
        directory:
            - "tests/"
        run_from: "phpunit/"
        webhooks:
           after:
               - http://example.com/testwebhook/{BuildName} 
```
