### ISSUE TITLE
How to get a really basic working build?

### ISSUE THREAD

**Issue by geoidesic** [Block8/PHPCI#1172]
At the moment I just get a slew of errors and I really can't figure out how to wade through them.

Is there like a basic yaml config that just disables all the plugins, so that one can enable them one by one while one figures out what each one does and how to configure it? 

I need some baby steps here and I feel like I'm very much in the deep end. Currently it is successfully fetching from git but codeception (whatever that is) is throwing errors. I would just like it to build successfully without running any plugins... just clone from git and be done so I can at least achieve a successful build, then we can start worrying about plugins.

**Comment by vinpel** [comment]
i have build a basic project just to test phpci and codeception, here are the result :

my basic phpci.yml :



```
build_settings:
    verbose: true
    prefer_symlink: false
    ignore:
      - "vendor"
setup:
  composer:
      directory: "."
      action: "install"
      prefer_dist: true
  shell:
    - "chmod 775 -R %BUILD_PATH%"
    - "%BUILD_PATH%/vendor/bin/codecept build"
test:
  codeception:
    config: codeception.yml
complete:
```
my composer.json : 

```
{
  "require": {

  },
  "require-dev":{
    "codeception/codeception": "~2.0.0",
    "codeception/phpbuiltinserver": "*"
  }
  

}

```

my codeception.yml (in the root directory)


```
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\PhpBuiltinServer
    config:
        Codeception\Extension\PhpBuiltinServer:
            hostname: localhost
            port: 8080
            autostart: true
            documentRoot: web
            startDelay: 1
            phpIni: /etc/php5/cli/php.ini

```

**Comment by MitchProbst** [comment]
When I first started up phpci, what sounds like was at the same time as you.  I was getting Codeception errors no matter what I did.  I ended up deleting it out of the package entirely because I could not get it to work.

As for disabling plugins I would mostly recommend to set up a phpci.yml with a blank tests section and then add in one test at a time as you walk through, that should assist you in simplifying this process.

My basic phpci.yml:
```
build_settings:
  verbose: false
  ignore:
    - "vendor"
    - "Tests"
    - "PHPCI/Command"
    - "public/install.php"
    - "PHPCI/Migrations"
    - "PHPCI/Model/Base"
    - "PHPCI/Languages"

setup:
  composer:
    action: "install"
    prefer_dist: false

test:
  php_mess_detector:
    allowed_warnings: 100
  php_code_sniffer:
    standard: "PSR2"
  php_docblock_checker:
    allowed_warnings: 100
```
So I would recommend removing all of these tests and then adding them back one at a time along with others that you deem necessary.
