### ISSUE TITLE
Intent to implement: Build status on Gitlab

### ISSUE THREAD

**Issue by lukzgois** [Block8/PHPCI#1178]
Hi everyone,
I'm planning to implement a way to show the build status on the gitlab commit pages. I do this in my project via the shell plugin, but I'm missing the status for pending and canceled builds.
I plan to make:

- Page to put the gitlab secret key
- Option to enable/disable buid status
- Update to the commit status when the buils status changes.

If anyone has a suggestion I'll be happy to listen hehe.

Thanks and bye :smile:

**Comment by REBELinBLUE** [comment]
👍

Would you mind sharing your shell script? Interested to see how this works as I have never gotten around to looking at the gitlab API

**Comment by lukzgois** [comment]
Hi @REBELinBLUE,
This is my script. Basically I just make a POST to the API passing the commit hash.

```
setup:
    composer:
        prefer_dist: "true"
    shell:
        - "curl -X POST -H 'PRIVATE-TOKEN: token' 'http://gitlab.mycompany.com/api/v3/projects/106/statuses/%COMMIT%?state=running&name=phpci'"
test:
success:
    shell:
        - "curl -X POST -H 'PRIVATE-TOKEN: token' 'http://gitlab.mycompany.com/api/v3/projects/106/statuses/%COMMIT%?state=success&name=phpci'"
failure:
    shell:
        - "curl -X POST -H 'PRIVATE-TOKEN: token' 'http://gitlab.mycompany.com/api/v3/projects/106/statuses/%COMMIT%?state=failed&name=phpci'"
```
