### ISSUE TITLE
Multiple config files for php unit in phpci.yml

### ISSUE THREAD

**Issue by WickedSilver** [Block8/PHPCI#1182]
Hi,

I'm trying to get our PHPCI build server to run with 2 phpunit configurations.
As stated in this [wiki](https://github.com/Block8/PHPCI/wiki/Adding-PHPCI-Support-to-Your-Projects) i put the following in my `phpci.yml` so that both of our bundles are tested:
```
test:
  php_unit:
      config:
      - "apps/loyalty/phpunit.xml.phpci"
      - "apps/spin/phpunit.xml.phpci"
```
But only the first PHPunit config file is being executed and the PHPunit plugin gave a FAILED, am i doing something wrong? Or is there a problem with my xml files?
