### ISSUE TITLE
Shell "install --help"

### ISSUE THREAD

**Issue by OxGroup** [Block8/PHPCI#1184]
Don't work shell
Write: install --help

> [2016-02-21 01:17:39] DaemoniseCommand.ERROR: install: пропущен операнд, задающий файл По команде «install --help» можно получить дополнительную информацию.  {"buildID":"150"} []

where he could do to take this option "install"?
phpci config:
```
build_settings:
    clone_depth: 1
    ignore:
        - "vendor"
        - "tests"
        - "migrations"
setup:
  composer:
    action: "install"
test:
  php_mess_detector:
        allow_failures: true
        allowed_warnings: -1
        allowed_errors: 0
  php_cpd:
        standard: "PSR2"
        allow_failures: true
        allowed_warnings: -1
        allowed_errors: -1
  php_loc:
        allow_failures: true
        allowed_warnings: -1
        allowed_errors: 0
  php_parallel_lint:
        allow_failures: false
        allowed_warnings: 0
        allowed_errors: 0
  php_code_sniffer:
        allow_failures: true
        standard: "PSR2"
        allowed_warnings: -1
        allowed_errors: 0
  php_docblock_checker:
        allow_failures: true
        allowed_warnings: -1
        allowed_errors: 0
        skip_classes: true
  php_unit:
        path: "tests/"
success:
  shell:
        - "rm -rf /home/realese"
        - "mv %BUILD_PATH% /home/realese"
```

**Comment by REBELinBLUE** [comment]
Sorry I am having trouble understanding, could you translate the error message as I can't figure it out?

**Comment by MitchProbst** [comment]
The error message roughly translated: 
```
[2016-02-21 01:17:39] DaemoniseCommand.Error: install: invalid argument in the given file. You can type install --help to receive additional information. {"buildID":"150"} [].
```
I believe what he is asking is where he is supposed to type this command because when he types "install --help" it obviously yields nothing.

OxGroup: this message is coming from composer, so you will want to type `composer install --help` to actually see what options are available.

Here is the output from the command: composer install --help
```
Usage:
  install [options] [--] [<packages>]...

Arguments:
  packages                       Should not be provided, use composer require instead to add a given package to composer.json.

Options:
      --prefer-source            Forces installation from package sources when possible, including VCS information.
      --prefer-dist              Forces installation from package dist even for dev versions.
      --dry-run                  Outputs the operations but will not execute anything (implicitly enables --verbose).
      --dev                      Enables installation of require-dev packages (enabled by default, only present for BC).
      --no-dev                   Disables installation of require-dev packages.
      --no-plugins               Disables all plugins.
      --no-custom-installers     DEPRECATED: Use no-plugins instead.
      --no-autoloader            Skips autoloader generation
      --no-scripts               Skips the execution of all scripts defined in composer.json file.
      --no-progress              Do not output download progress.
  -o, --optimize-autoloader      Optimize autoloader during autoloader dump
  -a, --classmap-authoritative   Autoload classes from the classmap only. Implicitly enables `--optimize-autoloader`.
      --ignore-platform-reqs     Ignore platform requirements (php & ext- packages).
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
 The install command reads the composer.lock file from
 the current directory, processes it, and downloads and installs all the
 libraries and dependencies outlined in that file. If the file does not
 exist it will look for composer.json and do the same.

 php composer.phar install
```

My composer section of my phpci config looks very similar to yours
```
setup:
  composer:
    action: "install"
    prefer_dist: false
```
