### ISSUE TITLE
Different commands based on branch

### ISSUE THREAD

**Issue by clubdeuce** [Block8/PHPCI#1209]
Is there a way to specify tasks that should only run for a specific branch?

In this use case, we have a series of tests that are being performed on every branch, Then, we want to run an rsync command when PHPCI is building the `master` branch.

**Comment by dancryer** [comment]
As of v1.7, yes - You can set up branch specific stages.  You add them like so:

```yml
branch-master:
    run-option: "after" # This can be set to either before, after or replace
    success:
        shell:
            - "rsync ..."
```
