### ISSUE TITLE
Format of email is not useful

### ISSUE THREAD

**Issue by roylindauer** [Block8/PHPCI#214]
The format of the email I get when a build fails is totally not useful. How can I change the output format for emails? Getting the raw data from the plugins would be ideal. As it is now I simply cannot parse out what is actually failing and what needs to be fixed. 

![screen shot 2013-11-21 at 11 03 04 am](https://f.cloud.github.com/assets/1851879/1594751/94f3b41a-52df-11e3-8a0e-a7f6cb75bc01.png)

Relevant portion of phpci.yml:

```
build_settings:
    verbose: false
complete:
    email: 
            addresses: 
                    - "my@company.com"
```
