### ISSUE TITLE
Could not connect to any read servers.

### ISSUE THREAD

**Issue by woganmay** [Block8/PHPCI#264]
So I get this big ugly block of text after trying to log in:

```
array(4) { ["message"]=> string(38) "Could not connect to any read servers." ["file"]=> string(50) "/vagrant/vendor/block8/b8framework/b8/Database.php" ["line"]=> int(122) ["trace"]=> string(712) "#0 /vagrant/PHPCI/Store/Base/UserStoreBase.php(54): b8\Database::getConnection('read') #1 /vagrant/PHPCI/Controller/SessionController.php(41): PHPCI\Store\Base\UserStoreBase->getByEmail('admin@phptestin...') #2 [internal function]: PHPCI\Controller\SessionController->login() #3 /vagrant/vendor/block8/b8framework/b8/Controller.php(67): call_user_func_array(Array, Array) #4 /vagrant/PHPCI/Controller.php(55): b8\Controller->handleAction('login', Array) #5 /vagrant/vendor/block8/b8framework/b8/Application.php(60): PHPCI\Controller->handleAction('login', Array) #6 /vagrant/PHPCI/Application.php(36): b8\Application->handleRequest() #7 /vagrant/public/index.php(18): PHPCI\Application->handleRequest() #8 {main}" } Notice: Undefined index: REDIRECT_PATH_INFO in /vagrant/PHPCI/Application.php on line 53 array(8) { ["PATH_INFO"]=> string(14) "/session/login" ["REDIRECT_PATH_INFO"]=> NULL ["REQUEST_URI"]=> string(14) "/session/login" ["PHP_SELF"]=> string(24) "/index.php/session/login" ["SCRIPT_NAME"]=> string(10) "/index.php" ["DOCUMENT_ROOT"]=> string(16) "/vagrant/public/" ["SCRIPT_FILENAME"]=> string(25) "/vagrant/public/index.php" ["SERVER_SOFTWARE"]=> string(22) "Apache/2.2.22 (Ubuntu)" }
```

My config.yml:

```
prevstage:
    - start
    - database
    - github
    - email
b8:
    database:
        servers:
            read:
                - localhost
            write:
                - localhost
        name: phpci
        username: root
        password: xYdfj5DltdKWxpzs
phpci:
    url: 'http://localhost:8080'
    github:
        id: ''
        secret: ''
    email_settings:
        smtp_address: ''
        smtp_port: ''
        smtp_encryption: on
        smtp_username: ''
        smtp_password: ''
        from_address: ''
        default_mailto_address: ''
```

This may be related to #263
