### ISSUE TITLE
Codeception Plugin path issue with database dump.sql

### ISSUE THREAD

**Issue by raistlin** [Block8/PHPCI#265]
Codeception plugin is unable to find my dump.sql file.
It says that it couldn't find src/tests/_data/dump.sql.

My codeception.yml file looks like

```
paths:
    tests: src/tests
    log: src/tests/_log
    data: src/tests/_data
    helpers: src/tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=test_db'
            user: 'user'
            password: 'password'
            dump: 'src/tests/_data/dump.sql'
            populate: true
            cleanup:  true
```

It seems that codeception working dir is not set up to %BUILD_PATH% properly, because if I disable database dumping (so codeception don't try to find that file, it runs properly)

As a workaround I added this very ugly lines to my phpci.yml setup section, and then file is found and codeception works

```
# Create link to src, needed for codeception
shell:
    - "ln -s %BUILD_PATH%/src src"
```

And these others to complete section to clean things up:

```
shell:
    - "unlink src"
```
