### ISSUE TITLE
PHPCS Run Against Multiple Directories

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#322]
I want to exclude all directories from PHPCS, except for two: app and public. All other files are irrelevant in regard to testing. I have tried the following without success:

```
    php_code_sniffer:
        path: "app"
        standard: "PSR1,PSR2"
    php_code_sniffer:
        path: "public"
        standard: "PSR1,PSR2"
```

It did not run at all.

```
    php_code_sniffer:
        path:
            - "app"
            - "public"
        standard: "PSR1,PSR2"
```

This threw an error, converting array to string, then failed.

How can I have PHPCS ignore all files in the project root, as well as all folders, except for two?

Thanks!
~Mike
