### ISSUE TITLE
IRC Plugin Not Working With Password-Secure IRC Servers

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#324]
I tried to get IRC to work, but I think I'm missing something. Here's what my phpci.yml file looks like:

```
build_settings:
    irc:
        server: "<username>:<server_password>@<server>.<tld>"
        room: "#<room_name>"
        nick: "<nickname>"
        port: 6667

success:
    irc:
        message: "Build succeeded."

failure:
    irc:
        message: "Build failed."
```

The keywords in < > I have set the corresponding values. (I also left out any settings that aren't relevant to IRC.) I'm confused as to how I would correctly connect to an IRC server that requires the following:
- Username
- Server Password
- Nickname
- Nickname Password (to register nick)

Also, is it possible to inject the build number and project name into the message?

Thanks!
