### ISSUE TITLE
PHPSpec Builds Fail

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#339]
After adding PHPSpec to phpci.yml, I get the following error in my builds, and none of them complete:

> [RuntimeException]  
>  The "-f" option does not exist.

The build log gives no indication as to why PHPSpec, failed, just says:

> RUNNING PLUGIN: phpspec
> PLUGIN STATUS: FAILED

Just to note: I have pulled the latest PHPCI using `git pull` on my machine before running this, to make sure I have any updates since my initial install, same result though. Here is my phpci.yml file, and I have phpspec.yml in my root directory:

```
build_settings:
    ignore:
        - "vendor"
        - "tests"
    mysql:
        host: "127.0.0.1"
        user: "phpci"
        pass: "xxxxxx"

setup:
    mysql:
        - "DROP DATABASE IF EXISTS test;"
        - "CREATE DATABASE test;"
        - "GRANT ALL PRIVILEGES ON test.* TO phpci@'localhost' IDENTIFIED BY 'xxxxxx';"
    composer:
        action: "install"

test:
    php_unit:
        config:
            - "phpunit.xml.dist"
        directory:
            - "app/tests/"
    phpspec:
    php_mess_detector:
        rules:
            - "build/phpmd.xml"
        allow_failures: false
    php_code_sniffer:
        path: "app"
        ignore:
            - "app/views"
        standard: "PSR1,PSR2"
    php_cpd:
        allow_failures: false
    php_loc:
        directory: "app"

complete:
    mysql:
        - "DROP DATABASE IF EXISTS test;"
```

 And here's my phpspec.yml:

```
suites:
  investorexpert_suite:
    namespace: App\Acme
    src_path: app
    spec_path: app
    spec_prefix: Spec
```
