### ISSUE TITLE
Code Coverage Graphs not showing

### ISSUE THREAD

**Issue by confact** [Block8/PHPCI#352]
I have a problem to make the graph for the Quality Trend and Lines of code graphs.
I have code coverage enabled and the tests doesn't give any errors.

this is my phpci.yml:

```
build_settings:
    ignore:
        - "vendor"
        - "phpunit"

setup:
    composer:
        action: "install"
test:
    php_unit:
        config:
            - "phpunit/phpunit.xml"
        run_from: "phpunit/"
        coverage: "build/coverage"

complete:

failure:
    email:
        committer: true
```

My phpunit.xml has this code coverage setting:

```
    <logging>
        <log type="coverage-html"
             target="build/coverage"
             charset="UTF-8"
             yui="true"
             highlight="true"
             lowUpperBound="35"
             highLowerBound="70"/>
   </logging>
```

What am I doing wrong, is this a bug?
