### ISSUE TITLE
PHP Mess Detector and uninitialized string offset

### ISSUE THREAD

**Issue by etki** [Block8/PHPCI#355]
Hi, i'm getting following error in build log:

> RUNNING PLUGIN: php_mess_detector
> > EXCEPTION: Notice: Uninitialized string offset: 0 in /srv/ci/php/PHPCI/Plugin/PhpMessDetector.php line 103
> PLUGIN STATUS: FAILED

([referenced place link](/Block8/PHPCI/blob/master/PHPCI/Plugin/PhpMessDetector.php#L103))

I guess that `$this->path` is set to an empty string in constructor and there is no 0 index at all, and referenced code should be replaced with following (or something like that):

```
if (strlen($this->path) > 0 && $this->path{0} == '/') {
    $path = $this->path;
}
```

I'm terribly sorry i'm not doing it via PR, i'm not 100% sure this is the place where error hides.

In case i'm wrong and problem lies elsewhere, my current mess detector config is:

```
php_mess_detector:
  rules:
    - codesize
    - unusedcode
    - naming
    - controversial
    - design
  allow_failures: true
```
