### ISSUE TITLE
TapParser only supports TAP version 13.

### ISSUE THREAD

**Issue by danmatthews** [Block8/PHPCI#393]
Seeing two errors when trying to build a laravel4 project, first, i don't think the composer plugin is working, and secondly, PHPUnit seems to not be working, and generating the TAP error below:

```
Cloning into '/var/phpci/PHPCI/build/project1-build10'...
Working copy created: /
RUNNING PLUGIN: env
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: composer
PLUGIN STATUS: FAILED
RUNNING PLUGIN: php_unit
EXCEPTION: TapParser only supports TAP version 13
PLUGIN STATUS: FAILED
BUILD FAILURE
Removing build.
```

My `phpci.yml`:

```
setup:
  env:
    TEST_DB_DB: "sss"
    TEST_DB_HOST: "127.0.0.1"
    TEST_DB_USER: "sss"
    TEST_DB_PWD: "sss"

  composer:
    action: "install"

test:
  php_unit:
    config:
      - "phpunit.xml"
    directory:
          - "app/tests/"

```
