### ISSUE TITLE
Lint plugin 'directory' option

### ISSUE THREAD

**Issue by luigi69** [Block8/PHPCI#452]
Documentation page for the lint plugin (https://github.com/Block8/PHPCI/wiki/Lint-plugin) mentions three options - directory, directories and recursive.

I've setup given configuration in 'Project details' tab:
```
test:
    lint:
        directory: "src/"
```
It doesn't work as expected - all directories are linted, whereas only the "src" directory should.

However given configuration works:
```
test:
    lint:
        directories:
            - "src/"
```
Now only this directory is linted.
Also it seems quite odd, that the following doesn't (no trailling slash):
```
test:
    lint:
        directories:
            - "src"
```
