### ISSUE TITLE
Error with simple phpci.yml: Undefined offset: -1 in PHPCI/Plugin/Util/TapParser.php

### ISSUE THREAD

**Issue by bpbp-boop** [Block8/PHPCI#467]
Hello,

I cannot work out what is causing this:

``` yml
build_settings:
  clone_depth: 1
  verbose: true
  prefer_symlink: false

setup:
  env:
    http_proxy: our proxy
    https_proxy: our proxy
  composer:
    action: "install"
    directory: "api/"

test:
    php_unit:
        run_from: "tests/"
        coverage: "/var/www/coverage"
        args: "--stderr"

complete:
```

```
Cloning into '/opt/phpci/PHPCI/build/project1-build33'...
Working copy created: /
RUNNING PLUGIN: env
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: composer
Using --prefer-source flag
Loading composer repositories with package information
Installing dependencies (including require-dev)
[etc]
Writing lock file
Generating autoload files
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: php_unit
TAP version 13
EXCEPTION: Notice: Undefined offset: -1 in /opt/phpci/PHPCI/Plugin/Util/TapParser.php line 46
PLUGIN STATUS: FAILED
BUILD FAILURE
Removing build.
```

I have a phpunit.xml file in the repo as well, with a simple testsuite entry pointing to 'tests/'
