### ISSUE TITLE
Simple build not respecting phpci.yml

### ISSUE THREAD

**Issue by Libbux** [Block8/PHPCI#483]
On a clean installation, a simple build of this PHPCI repository is not respecting `phpci.yml`. When I make a change to the file (such as deleting the `php_code_sniffer` and `php_mess_detector` plugins, as they were causing builds to fail (!)), the updated parameters do not seem to be respected in the next build (correct me if I don't understand the configuration properly).

Here is the `phpci.yml` file for the project, modified to stop the `php_code_sniffer` and `php_mess_detector` plugins from running:

``` yaml

build_settings:
  verbose: false
  ignore:
    - "vendor"
    - "Tests"
    - "PHPCI/Command" # PHPMD complains about un-used parameters, but they are required.
    - "public/install.php" # PHPCS really doesn't like PHP mixed with HTML (and so it shouldn't)

setup:
  composer:
    action: "install"
    prefer_dist: false

test:
  php_loc:
  php_unit:
  php_docblock_checker:
    allowed_warnings: -1 # Allow unlimited warnings for now.

failure:
  email:
    committer: false
    cc: ["x@example.com"]
```

And here is the part of the build log that leads me to believe that the plugins are still being run:

```
...
Generating autoload files
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: php_mess_detector
PLUGIN STATUS: FAILED
RUNNING PLUGIN: php_code_sniffer
PLUGIN STATUS: FAILED
RUNNING PLUGIN: php_loc
...
```
