### ISSUE TITLE
PHPUnit runs tests, but does not show the results afterwards.

### ISSUE THREAD

**Issue by StephanHeijl** [Block8/PHPCI#486]
When I submit a build to PHPCI, PHPUnit is initialized and runs the tests. This can be seen in the build window under the PHPUnit header, all tests are run. Some of them have failed, however, but the output of PHPUnit is not shown in the console.

Below is my console output:

```
Working copy created: /
RUNNING PLUGIN: php_unit
PLUGIN STATUS: FAILED
RUNNING PLUGIN: php_mess_detector
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: php_loc
phploc 2.0.6 by Sebastian Bergmann.

[cut for brevity]
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: php_docblock_checker
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: email
1 emails sent
0 emails failed to send
PLUGIN STATUS: SUCCESS!
BUILD FAILURE
Removing build.
```

This is my phpunit.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
>
    <testsuites>
        <testsuite name="Laravel test suite">
            <directory>./app/tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

And this is my phpci.yml

```
build_settings:
  verbose: true
  ignore:
    - "vendor"
    - "app/tests"
    - "public/install.php" # PHPCS really doesn't like PHP mixed with HTML (and so it shouldn't)
    - "bootstrap"
    - "app/database"
test:
  php_unit:
  php_mess_detector:
    allowed_warnings: -1
  php_loc:
  php_docblock_checker:
    allowed_warnings: -1 # Allow unlimited warnings for now.

failure:
  email:
    committer: true
    cc: ["removed"]
```

I have tried running phpunit with `args: --verbose`, but this did not yield a different result.
Running PHPUnit directly produces the expected results, even with `--tap`. The correct tests are shown under the PHPUnit header, so I presume that PHPUnit has had no problems starting. Am I missing a parameter or some sort of configuration?
