### ISSUE TITLE
Codeception config

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#526]
Hi

In the repository that I'm building, I have a folder `tests` which contains some acceptance tests.

The problem is, there is no real documentation on how I'd get these to run during the build.

The page: https://github.com/Block8/PHPCI/wiki/Codeception-plugin mentions using a codeception configuration file:

I have this in my `phpci.yml`

```
test:
    codeception:
        config: "codeception.yml"
        args: "acceptance"
```

Does anyone have an example of what needs to go in this file? Is it pretty much the same as the Codeception `acceptance.suite.yml` file?
