### ISSUE TITLE
Ignoring phpci.yml file

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#530]
Hi

I have the folllowing phpci.yml

```
test:
  codeception:
    config: "codeception.yml"
    args: -vvv
  php_mess_detector:
    allowed_warnings: 0
  php_code_sniffer:
    standard: "PSR1,PSR2"
    allowed_errors: -1
    allow_warnings: -1
  php_loc:
  php_unit:
  php_docblock_checker:
    allowed_warnings: -1
  php_cpd:
```

When the build is run, I see the following plugins being ran:

`RUNNING PLUGIN: \PHPCI\Plugin\PhpCodeSniffer`
`RUNNING PLUGIN: \PHPCI\Plugin\PhpDocblockChecker`
`RUNNING PLUGIN: \PHPCI\Plugin\PhpLoc`
`RUNNING PLUGIN: \PHPCI\Plugin\PhpMessDetector`

You can see I have codeception and php_cmd plugins defined.

Is there any reason why these are never called?

I have looked in `Builder.php` and var_dump'd out `$stage` in the foreach in `execute()`, which returned the following:

```
'test' =>
  array(4) {
    '\PHPCI\Plugin\PhpCodeSniffer' =>
    array(1) {
      'zero_config' =>
      bool(true)
    }
    '\PHPCI\Plugin\PhpDocblockChecker' =>
    array(1) {
      'zero_config' =>
      bool(true)
    }
    '\PHPCI\Plugin\PhpLoc' =>
    array(1) {
      'zero_config' =>
      bool(true)
    }
    '\PHPCI\Plugin\PhpMessDetector' =>
    array(1) {
      'zero_config' =>
      bool(true)
    }
  }
```

So it seems that these 4 plugins are the only ones that are ever run.

coincidentally, If I have an empty phpci.yml, these 4 plugins are still run, which seems to suggest that it is ignoring my phpci.yml
