### ISSUE TITLE
Segmentation Fault while running the cron.

### ISSUE THREAD

**Issue by nmrsmn** [Block8/PHPCI#596]
Im getting this error in my root mail (/var/spool/mail/root) while executing the build cron:

/bin/sh: line 1:  9802 Segmentation fault      /usr/bin/php /var/www/xxxx/console phpci:run-builds > /dev/null

``` yml
[phpci.yml]
build_settings:
  verbose: true
  ignore:
    - "vendor"
    - "tests"

setup:
  composer:
    action: "install"
    prefer_dist: false

test:
  php_mess_detector:
    allowed_warnings: 0
  php_code_sniffer:
    standard: "PSR2"
    allowed_warnings: 0
    allowed_errors: 0
  php_loc:
  php_unit:
    directory:
      - "tests/"
  php_docblock_checker:
    allowed_warnings: -1
```

If I remove everything within php_unit I won't get the segmentation fault, with the phpci.yml like above it gives me the segmentation fault...

What's wrong?
