### ISSUE TITLE
PhpUnit reporting Failed but Tests were successful

### ISSUE THREAD

**Issue by jiminald** [Block8/PHPCI#599]
I'm using the PHPUnit example in PHPCI on a fresh build and seeing that the plugin is reporting back that the tests failed but in the list below, all the tests are green.

![image](https://cloud.githubusercontent.com/assets/459842/4263926/df76b748-3c0a-11e4-9081-595a0dd74f8d.png)

![image](https://cloud.githubusercontent.com/assets/459842/4263929/f2ebb7c4-3c0a-11e4-875b-3c051808d56f.png)

Config
```
build_settings:
    verbose: true

test:
    php_unit:
        config: 'phpunit.xml'
        directory: 'tests'
```

I've ran the tests manually and they come back with no errors
![image](https://cloud.githubusercontent.com/assets/459842/4263935/b6cc42c6-3c0b-11e4-90bf-ef10964d87f1.png)
