### ISSUE TITLE
Vendor folder missing after build composer

### ISSUE THREAD

**Issue by MrFloppy** [Block8/PHPCI#728]
I am running project which depends on the composer autoloader.

This is my tiny config:
```
build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo

	setup:
    composer:
        action: "install"

test:
	php_unit:
		directory: "tests"
		run_from: ""
		args: "-c phpunit.xml"
```

After composer finishes the setup successfully my phpunit crashes:
```
Generating autoload files
PLUGIN: SUCCESS
RUNNING PLUGIN: php_unit
PHP Warning:  require_once(vendor/autoload.php)
```
Looking into the build folders the vendor folder was missing. During the setup it is present but then it gets lost... 
What do I do wrong?

**Comment by tvbeek** [comment]
You need to remove the spaces before setup.

Then you get
```
build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo

setup:
    composer:
        action: "install"

test:
	php_unit:
		directory: "tests"
		run_from: ""
		args: "-c phpunit.xml"
```
