### ISSUE TITLE
Class 'Codeception\AbstractGuy' not found

### ISSUE THREAD

**Issue by DrRoach** [Block8/PHPCI#743]
I am getting this error whenever I try and run a build: `RunCommand.ERROR: PHP Fatal error:  Class 'Codeception\AbstractGuy' not found`

My codeception.yml looks like this:
```yml
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```
and my phpci.yml looks like this:
```yml
setup:
    composer:
        action: "install"
test:
    codeception:
        config: "."
```

**Comment by tvbeek** [comment]
Did you locally has give the build command ( php codecept.phar build ) and that the generated files are in your repository?

**Comment by DrRoach** [comment]
No, sorry I forgot to say, it is using a bitbucket repository so I can't run codecept build

**Comment by tvbeek** [comment]
if you have access to the repository you can add it. Else you need to enable the shell plugin and add a command to run the build command in your setup.

Like:
```yml
setup:
    composer:
        action: "install"
    shell:
        - "cd %PHPCI_BUILD_PATH% && codecept build"
```

**Comment by DrRoach** [comment]
Awesome, that worked, do you know if there is any future aim to add a bit more documentation to make this a bit clearer? Also my test now failed on "I am on page '/'" will assertions like that not be possible anymore? The test runs fine on my local machine

**Comment by tvbeek** [comment]
On the PHPCI server you have by default not a running website to test the acceptance test.
I use shell commands and a script to start and stop a local server (the internal php server) to test it.
I copy my sample files for the codeception test (the codeception.yml and acceptance.suite.yml are in my gitignore)
The last shell command is to call the server, that is a sh script.
In the complete part I stop the server

The phpci.yml parts for the tests are:
```yml
setup:
    composer:
        action: "install"
    shell:
        - "cp %PHPCI_BUILD_PATH%/tests/acceptance.suite.yml.sample %PHPCI_BUILD_PATH%/tests/acceptance.suite.yml"
        - "cp %PHPCI_BUILD_PATH%/codeception.yml.sample %PHPCI_BUILD_PATH%/codeception.yml"
        - "cp %PHPCI_BUILD_PATH%/test.env %PHPCI_BUILD_PATH%/.env"
        - "chmod +x %PHPCI_BUILD_PATH%/*.sh"
        - "%PHPCI_BUILD_PATH%/reset_sqlite.sh"
        - "cd %PHPCI_BUILD_PATH% && codecept build"
        - "cd %PHPCI_BUILD_PATH% && ./start_server.sh && less pid"

test:
    codeception:
        config: "."

complete:
    shell:
        - "cd %PHPCI_BUILD_PATH% && ./stop_server.sh"
```

start_server.sh, the port need to be the same as the port in acceptance.suite.yml
```sh
nohup  php -S 127.0.0.1:8080 -t public/ > /dev/null 2>&1&
echo $! > pid
```

stop_server.sh
```sh
kill -9 `cat pid`
rm pid
```
