### ISSUE TITLE
Daemonised builds: sh: 0: getcwd() failed: No such file or directory

### ISSUE THREAD

**Issue by tomasstrejcek** [Block8/PHPCI#799]
I cannot run my builds using daemonise, because the process cant run getcwd and fails.
When using cron, multiple pushes to many branches always overload server/mysql so I need to run one build at a time.

I am using shell plugin, so maybe it has some effect on this?

(complete build log:)

sh: 0: getcwd() failed: No such file or directory
fatal: Could not get current working directory: No such file or directory

Failed to clone remote git repository.
Exception: Could not create a working copy.

additional info: first build works, second (manual or triggered via webhook fails with message above)

**Comment by tomasstrejcek** [comment]
okay, the same happens with current dev-maste in phpci:run-builds ..

**Comment by tomasstrejcek** [comment]
caused by plugin

**Comment by EmmanuelVella** [comment]
I have the same issue, which plugin causes this error ?

**Comment by JonathanMarmitt** [comment]
Hi!
I am in the same situation, but i'm not sure if the problem is caused by a plugin, because i can rebuild by command line without this error, but when i try to build by the web application, every project in every repository type cause this error.

**Comment by r3sist** [comment]
Same here.

**Comment by jankal** [comment]
Definitly not fixed and ready to close yet @tomasstrejcek!
I'm also encountering this issue when fireing a webhook in a fresh install using
```
`build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
    ignore:
        - "vendor"

setup:
    composer:
        action: "install"

test:
    lint:
        directory: "src/"
        recursive: true
    php_docblock_checker:
        allowed_warnings: 0
    php_spec:
    php_unit:
        config:
            - "/phpunit.xml"
    php_mess_detector:
        allow_failures: true
    php_code_sniffer:
        standard: "PSR2"
    php_cpd:
        allow_failures: true
    php_loc:
        directory: "src"
```
with PHPCI `1.7.1`
So no `Shell Plugin` and no foreign plugins from other devs yet. This is an issue concerning PHPCI.

Manually starting the build works as expected.

```
shell-init: Kann das aktuelle Verzeichnis nicht wiederfinden: getwd: Kann auf das übergeordnete Verzeichnis nicht zugreifen.: Datei oder Verzeichnis nicht gefunden
fatal: Could not get current working directory: Datei oder Verzeichnis nicht gefunden

Failed to clone remote git repository.
Exception: Could not create a working copy.
E_WARNING: array_key_exists() expects parameter 2 to be array, null given


Warning: array_key_exists() expects parameter 2 to be array, null given in /data/var_www/domains/alexanderjank.de/subdomains/ci/PHPCI/Plugin/Util/Executor.php line 56
```
@tomasstrejcek Thanks!
