### ISSUE TITLE
pdepend plugin throws Invalid directory error

### ISSUE THREAD

**Issue by torrentalle** [Block8/PHPCI#808]
I'm trying to configure **pdepend** plugin and I can't configure directory option.
Always I get *Invalid directory* error

**phpci.yml**
````
build_settings:
    verbose: true
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo

setup:
    env:
        APP_ENV: "testing"

test:
    pdepend:
       directory: "app"
````
I get this error in **build log**

````
RUNNING PLUGIN: pdepend
PDepend 2.0.4
Critical error: 
=============== 
Invalid directory 'app' added.
PLUGIN: FAILED
BUILD FAILED
````

My Project structure is:

````
  /
  | phpci.yml
  | app/
      | Numbers/
         | One.php
         | Two.php
````

This is caused because the pdepend command is executed in HOME dir of user that cron or daemon runs. **It shloud be executed passing the build path to the pdepend command**
