### ISSUE TITLE
Adding slack notify causes PHP Error

### ISSUE THREAD

**Issue by awomersley** [Block8/PHPCI#811]
When I add the following to my phpci.yml file..

```
complete:
  slack_notify:
    webhook_url: "https://hooks.slack.com/services/abc123"
    room: "#phpci"
    username: "PHPCI"
```

I get the following error on the main dashboard page

```
Fatal error: Call to a member function format() on a non-object in /var/www/phpci/PHPCI/View/Home/index.phtml on line 47
```

I have to delete the build from the DB to get the site back functioning. If i then remove the 'slack notify' command from the yml file and build again it all work fine.

I am running latest version.
