### ISSUE TITLE
sh: 1: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by olimsaidov** [Block8/PHPCI#862]
I'm getting `sh: 1: Syntax error: Unterminated quoted string` error:

```
PLUGIN: SUCCESS
RUNNING PLUGIN: php_unit
PLUGIN: SUCCESS
RUNNING PLUGIN: php_mess_detector
sh: 1: Syntax error: Unterminated quoted string


Exception: Could not process PHPMD report XML.
PLUGIN: FAILED
RUNNING PLUGIN: php_code_sniffer
sh: 1: Syntax error: Unterminated quoted string


Exception: Could not process the report generated by this tool.
PLUGIN: FAILED
RUNNING PLUGIN: php_cpd
sh: 1: Syntax error: Unterminated quoted string


Exception: Could not process the report generated by this tool.
PLUGIN: FAILED
RUNNING PLUGIN: php_docblock_checker
sh: 1: Syntax error: Unterminated quoted string

Exception: Warning: Invalid argument supplied for foreach() in /opt/phpci/PHPCI/Plugin/PhpDocblockChecker.php line 167
PLUGIN: FAILED
RUNNING PLUGIN: php_loc
sh: 1: Syntax error: Unterminated quoted string

PLUGIN: FAILED
BUILD FAILED
Removing Build.
```

phpci.yaml file: 

```
build_settings:
    clone_depth: 1
    ignore:
        - vendor
        - bin"
        - app

setup:
    composer:
        action: install
        prefer_dist: true

test:
    php_unit:
        config:
            - app/phpunit.xml.dist

    php_mess_detector:
        allow_failures: true

    php_code_sniffer:
        standard: Symfony2

    php_cpd:
        allow_failures: true

    php_docblock_checker:
        allowed_warnings: 10
        skip_classes: true

    php_loc:
        directory: src
```

PHPCI composer.json:

```
...
    "require": {
        "php": ">=5.3.8",
        "ext-pdo": "*",
        "ext-pdo_mysql": "*",
        "block8\/b8framework": "~1.0",
        "ircmaxell\/password-compat": "~1.0",
        "swiftmailer\/swiftmailer": "~5.0",
        "symfony\/yaml": "~2.1",
        "symfony\/console": "~2.1",
        "psr\/log": "~1.0",
        "monolog\/monolog": "~1.6",
        "pimple\/pimple": "~1.1",
        "robmorgan\/phinx": "~0.4",
        "phploc\/phploc": "dev-master",
        "fabpot\/php-cs-fixer": "dev-master",
        "sebastian\/phpcpd": "dev-master",
        "jakub-onderka\/php-parallel-lint": "dev-master",
        "squizlabs\/php_codesniffer": "@stable",
        "phpmd\/phpmd": "2.2.1"
    },
...
```
