### ISSUE TITLE
Code Sniffer Plugin: Failed

### ISSUE THREAD

**Issue by Sekonda** [Block8/PHPCI#906]
Maybe I'm doing something silly, or haven't installed PHPCI correctly, but I keep getting 'PLUGIN FAILED' for *php_code_sniffer".

Below are my build settings:
```
test: 
  php_code_sniffer: 
    allowed_warnings: 2
    ignore: 
      - tests
      - src/autoload.php
    path: src
    standard: PSR2
  php_docblock_checker: 
    allowed_warnings: 2
  php_unit: 
    args: "--bootstrap src/autoload.php"
    path: tests
```

Below is the build output:
```
Cloning into '/var/www/PHPCI/PHPCI/build/25'...

Working copy created: /
RUNNING PLUGIN: php_unit
PLUGIN: SUCCESS
RUNNING PLUGIN: php_mess_detector
PLUGIN: SUCCESS
RUNNING PLUGIN: php_code_sniffer
PLUGIN: FAILED
RUNNING PLUGIN: php_cpd
phpcpd 2.0.2 by Sebastian Bergmann.
0.00% duplicated lines out of 174 total lines of code.
Time: 27 ms, Memory: 3.00Mb
PLUGIN: SUCCESS
BUILD FAILED
Removing Build.
```

I do get a single code sniffer warning on the autoload.php file even though it's been set to ignore that file. 

Any ideas?

**Comment by mikebronner** [comment]
Try adding:

build_settings:
  verbose: true

above your test section. That may help shed more light on the failure. Another method to debug I use is to run the build command from the command line to see what the output there is (you tend to get more output).

~Mike

**Comment by Sekonda** [comment]
I took a look over everything this morning and put all of the config into files rather than in the project on phpci. 

**phpci.yml**
```
build_settings:
  verbose: true
test: 
  php_docblock_checker:
    allowed_warnings: 2
    path: src
  php_unit:
    config: "phpunit.xml"
    directory:
      - "tests"
  php_code_sniffer:
    allowed_warnings: 2
    ignore: 
      - tests
      - src/autoload.php
    path: src
    standard: PSR2

```

Builds fine, but adding in: 

```
test: 
  php_loc:
    directory:
      - "src"

```

throws out: 

```
Exception: Notice: Array to string conversion in /var/www/PHPCI/PHPCI/Plugin/PhpLoc.php line 62
```

**Comment by Sekonda** [comment]
Okay, apologies for the close, then immediately update. I changed 

```
test: 
  php_loc:
    directory:
      - "src"
```

to

```
test: 
  php_loc:
    directory: "src"
```

and it built fine.
