### ISSUE TITLE
Mail notification template

### ISSUE THREAD

**Issue by Adirelle** [Block8/PHPCI#907]
Would it possible to select the template used for notification using a parameter instead of the build outcome ? I'd like failed builds to send a mail with the full log while successful builds could just send a short notice.

(This could be used on the instance that tests the Github project to send feedback about PRs.)

**Comment by tvbeek** [comment]
You mean like a default template and an option to change it
```
email:
        committer: true
        default_mailto_address: one@example.com
        template: with_logs
```

I think that is a nice feature
