### ISSUE TITLE
Could not read "/app/phpunit.xml".

### ISSUE THREAD

**Issue by ivaaaan** [Block8/PHPCI#969]
My phpci.yml in /project:
```
test:
    php_unit:
        config:
            - "app/phpunit.xml"
        path: "app/"
```

And my phpunit.xml in /project/app. Why i get this error?

If i run in my console:
`$ phpunit -c app/` - all ok

**Comment by ivaaaan** [comment]
I solved it:
```
build_settings:
    ignore:
        - "vendor"
        - "tests"

setup:
    composer:
        action: "update"

test:
    php_unit:
        config:
            - "app/phpunit.xml"
```
